//console.log("Hello my friend");
//console.log("Hello my\nfriend");
//console.log("Hello my \"friend\"");
//console.log("Hello my \'friend\'");
//console.log("hello \\my friend");
//console.log("hello\tmy friend")
//console.log('\u{1F4A9}');
//console.log("abc" > "aac");
//console.log("3" < "a");
//console.log("5" - 1);
//console.log("5" + 1);
//console.log("five" - 1);
//console.log(3 < "a");
//console.log("3" < "a");
//console.log("3" > 1);
//console.log(3 != 3);
//console.log(true >= 0);
//console.log(typeof(true));
//console.log(typeof([]));
//console.log(Array.isArray([]));
//console.log(0 == false);
//console.log(1 == true);
//console.log("" == false);
//console.log(false == []);
//console.log("" == 0);
//console.log("" == []);
//console.log("Hello" + 1 + "Julia");
//console.log("Hello" % 10); 
//console.log(NaN === NaN);
//console.log(undefined === undefined);
//console.log(null === null);
//console.log([] === []);
//console.log([1] === [1]);
//console.log({} === {});
//console.log(null == undefined);
//console.log(null === undefined);
//console.log(null == 0);
//console.log(false || true);
//console.log(false || false);
//console.log("Johan" || "Andres");
//console.log("" || "Andres");
//console.log(1 || "Andres");
//console.log(0 || "Andres");
//console.log(-1 || "Andres");
//console.log([] || "Andres");
//console.log(true || "Andres");
//console.log(false || "Andres");
//console.log(null || "Andres");
//console.log(NaN || "Andres");
//console.log(undefined || "Andres");
//console.log(false && true);
//console.log(false && false);
//console.log("Johan" && "Andres");
//console.log("" && "Andres");
//console.log(1 && "Andres");
//console.log(0 && "Andres");
//console.log(-1 && "Andres");
//console.log([] && "Andres");
//console.log(true && "Andres");
//console.log(false && "Andres");
//console.log(null && "Andres");
//console.log(NaN && "Andres");
//console.log(undefined && "Andres");

if (NaN) {
    console.log("truthy");
} else {
    console.log("falsy");
}